-- =====================================================
-- SNOWFLAKE INTELLIGENCE SETUP
-- =====================================================

-- Allow full access to all regions
USE ROLE ACCOUNTADMIN;
-- https://docs.snowflake.com/en/user-guide/snowflake-cortex/cross-region-inference
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Start the setup
USE ROLE SYSADMIN;

-- Create the database and schema to store Snowflake Intelligence agents
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;  -- DB for a Snowintelligence Agents
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.PUBLIC; -- Schema for public services
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS; -- Schema for public AGENTS
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS ;  -- Example schema sales_insights services (adjust as needed)

--CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.<GROUP2_INSIGHTS>;  -- Add as needed

-- ####################################################
-- SETUP GRANTS TO SNOWFLAKE INTELLIGENCE
-- ####################################################

USE ROLE SECURITYADMIN;

-- Create Public Snowflake Intelligence User role
CREATE ROLE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Enables access to Cortex AI functionality
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the public schema
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the public schema

-- Uncomment/edit/execute as needed to grant access to public agents, search services, semantic views, and custom tools (stored procedures)
--GRANT USAGE ON CORTEX SEARCH SERVICE SNOWFLAKE_INTELLIGENCE.PUBLIC.<PUBLIC_SEARCH_SERVICE> TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access a public search service
--GRANT REFERENCES, SELECT ON SEMANTIC VIEW SNOWFLAKE_INTELLIGENCE.PUBLIC.<PUBLIC_SEMANTIC_VIEW> TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access a public semantic view (cortex analyst)
--GRANT USAGE ON PROCEDURE SNOWFLAKE_INTELLIGENCE.PUBLIC.<PUBLIC_STORED_PROCEDURE>(...) TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access a public stored procedure
--GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.<PUBLIC_AGENT> TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access the public agent

-- Grant out to the Sales Insights Developer community (Repeat for each group)
CREATE ROLE IF NOT EXISTS SALES_INSIGHTS_DEV_GROUP ;
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- Sales insights devs can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- Sales insights devs can access the public schema
GRANT CREATE SEMANTIC VIEW ON SCHEMA SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP; -- grant create semantic views for cortex analyst to sales insights devs
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP; -- grant create cortex search service to sales insights devs
GRANT CREATE PROCEDURE ON SCHEMA SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP; -- grant create procedures to sales insights devs
GRANT CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- Sales insights devs can create agents for Snowflake Intelligence

-- Grant out to the Sales Insights User community (Adjust naming, Repeat for each group)
CREATE ROLE IF NOT EXISTS SALES_INSIGHTS_USER_GROUP ;
GRANT ROLE SALES_INSIGHTS_USER_GROUP TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- SI ADMINS can access the SI PUBLIC USER role
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SALES_INSIGHTS_USER_GROUP;  -- Sales insights users can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_USER_GROUP;  -- Sales insights users can access the public schema

-- Uncomment/edit/execute as needed to grant access to non-public agents, search services, semantic views, and custom tools (stored procedures)
--GRANT USAGE ON CORTEX SEARCH SERVICE SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS.<USE_CASE_SEARCH_SERVICE> TO ROLE SALES_INSIGHTS_USER_GROUP; -- Sales insights users can access a non-public search service
--GRANT REFERENCES, SELECT ON SEMANTIC VIEW SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS.<USE_CASE_VIEW> TO ROLE SALES_INSIGHTS_USER_GROUP; -- Sales insights users can access a non-public semantic view (cortex analyst)
--GRANT USAGE ON PROCEDURE SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS.<USE_CASE_STORED_PROCEDURE>(...) TO ROLE SALES_INSIGHTS_USER_GROUP; -- SI USERS can access a non-public stored procedure
--GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.<USE_CASE_AGENT> TO ROLE CREATE ROLE SALES_INSIGHTS_USER_GROUP;  -- Sales insights users can access a non-public agent

-- Create Snowflake Intelligence Admin role
CREATE ROLE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can access the SI PUBLIC USER role
GRANT ROLE SALES_INSIGHTS_DEV_GROUP TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can access the SI SALES INSIGHTS DEV GROUP role
GRANT ROLE SALES_INSIGHTS_USER_GROUP TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can access the SI SALES INSIGHTS USER GROUP role
GRANT CREATE SEMANTIC VIEW ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- Only admins can create public semantic views for cortex analyst 
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- Only admins can create public cortex search service
GRANT CREATE PROCEDURE ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- grant create procedures to sales insights devs
GRANT CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can create public agents


-- Grant out to the users
GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO ROLE PUBLIC; -- Everyone can use Snowflake Intelligence
GRANT ROLE SNOWFLAKE_INTELLIGENCE_ADMIN TO user <username1> ; -- Allocate out to admins (repeat as needed)
GRANT ROLE SALES_INSIGHTS_DEV_GROUP TO user <username2> ; -- Allocate out to devs (repeat as needed)
GRANT ROLE SALES_INSIGHTS_USER_GROUP TO user <username3> ; -- Allocate out to users (repeat as needed)


-- SHOW GRANTS TO CORTEX UESR
SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.CORTEX_USER;
SHOW GRANTS OF ROLE SNOWFLAKE_INTELLIGENCE_USER;
SHOW GRANTS OF ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
SHOW GRANTS OF ROLE SALES_INSIGHTS_DEV_GROUP;
SHOW GRANTS OF ROLE SALES_INSIGHTS_USER_GROUP;
