-- =====================================================
-- SNOWFLAKE INTELLIGENCE SETUP
-- =====================================================

USE ROLE SECURITYADMIN;

-- Create Snowflake Intelligence Admin role
CREATE ROLE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_ADMIN;


-- Allow full access to all regions
USE ROLE ACCOUNTADMIN;
-- https://docs.snowflake.com/en/user-guide/snowflake-cortex/cross-region-inference
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
--https://docs.snowflake.com/en/user-guide/snowflake-cortex/snowflake-intelligence#grant-sf-intelligence-privileges

-- Allow adding/removing of agents from Snowflake Intelligence UI
GRANT MODIFY ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;


-- Start the setup
USE ROLE SYSADMIN;

-- Create the database and schema to store public agents
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;  -- DB for a public Agents
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.PUBLIC; -- Schema for public services
CREATE SCHEMA IF NOT EXISTS EDW.SALES_INSIGHTS ;  -- Example schema in an existing EDW database for sales_insights services (adjust as needed)

--CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.<GROUP2_INSIGHTS>;  -- Add as needed

-- ####################################################
-- SETUP GRANTS TO SNOWFLAKE INTELLIGENCE
-- ####################################################

USE ROLE SECURITYADMIN;

-- Grants for Snowflake Intelligence Admin role (created above)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- Enables access to Cortex AI functionality
GRANT CREATE SEMANTIC VIEW ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- Only SI admins can create public semantic views for cortex analyst 
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- Only SI admins can create public cortex search service
GRANT CREATE PROCEDURE ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- Only SI admins can create public procedures for custom tools
GRANT CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- Only SI admins can can create public agents


-- Create Public Snowflake Intelligence User role
CREATE ROLE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_USER;
GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- SI ADMINS can access the SI PUBLIC USER role
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Enables access to Cortex AI functionality
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the public schema
GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can access the SI PUBLIC USER role


-- Grant out to the Sales Insights Developer community (Adjust naming, Repeat for each group)
CREATE ROLE IF NOT EXISTS SALES_INSIGHTS_DEV_GROUP ;
GRANT ROLE SALES_INSIGHTS_DEV_GROUP TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can access the SI SALES INSIGHTS DEV GROUP role
GRANT USAGE ON DATABASE EDW TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- Sales insights devs can access the DB
GRANT USAGE ON SCHEMA EDW.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- Sales insights devs can access the sales insights schema
GRANT CREATE SEMANTIC VIEW ON SCHEMA EDW.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP; -- grant create semantic views for cortex analyst to sales insights devs
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA EDW.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP; -- grant create cortex search service to sales insights devs
GRANT CREATE PROCEDURE ON SCHEMA EDW.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP; -- grant create procedures to sales insights devs
GRANT CREATE AGENT ON SCHEMA EDW.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- Sales insights devs can create agents


-- Grant out to the Sales Insights User community (Adjust naming, Repeat for each group)
CREATE ROLE IF NOT EXISTS SALES_INSIGHTS_USER_GROUP ;
GRANT ROLE SALES_INSIGHTS_USER_GROUP TO ROLE SALES_INSIGHTS_DEV_GROUP;  -- DEVs can access the SI SALES INSIGHTS USER GROUP role
GRANT ROLE SALES_INSIGHTS_USER_GROUP TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can access the SI SALES INSIGHTS USER GROUP role
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SALES_INSIGHTS_USER_GROUP;  -- Sales insights users can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.SALES_INSIGHTS TO ROLE SALES_INSIGHTS_USER_GROUP;  -- Sales insights users can access the public schema


-- Grant out to the users
GRANT ROLE SNOWFLAKE_INTELLIGENCE_ADMIN TO user <username1> ; -- Allocate out to admins (repeat as needed)
GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO ROLE PUBLIC; -- Everyone can use Snowflake Intelligence
--GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO user <username1> ; -- Explict grant if not using PUBLIC role
GRANT ROLE SALES_INSIGHTS_DEV_GROUP TO user <username2> ; -- Allocate out to devs (repeat as needed)
GRANT ROLE SALES_INSIGHTS_USER_GROUP TO user <username3> ; -- Allocate out to users (repeat as needed)


-- Grant access to new agents
GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.PUBLIC.<PUBLIC_AGENT> TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access the public agent
ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT ADD AGENT SNOWFLAKE_INTELLIGENCE.PUBLIC.<PUBLIC_AGENT>; -- Add public agent to Snowflake Intelligence UI
GRANT USAGE ON AGENT EDW.SALES_INSIGHTS.<USE_CASE_AGENT> TO ROLE CREATE ROLE SALES_INSIGHTS_USER_GROUP;  -- Sales insights users can access a non-public agent
ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT ADD AGENT EDW.SALES_INSIGHTS.<USE_CASE_AGENT>; -- Add non-public agent to Snowflake Intelligence UI


-- SHOW GRANTS TO CORTEX UESR
SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.CORTEX_USER;
SHOW GRANTS OF ROLE SNOWFLAKE_INTELLIGENCE_USER;
SHOW GRANTS OF ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
SHOW GRANTS OF ROLE SALES_INSIGHTS_DEV_GROUP;
SHOW GRANTS OF ROLE SALES_INSIGHTS_USER_GROUP;
SHOW SNOWFLAKE INTELLIGENCES;
