-- =====================================================
-- SNOWFLAKE INTELLIGENCE SETUP
-- =====================================================

-- Allow full access to all regions
USE ROLE ACCOUNTADMIN;
-- https://docs.snowflake.com/en/user-guide/snowflake-cortex/cross-region-inference
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Start the setup
USE ROLE SYSADMIN;

-- Create the database and schema to store Snowflake Intelligence agents
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;  -- DB for agents
DROP SCHEMA IF EXISTS SNOWFLAKE_INTELLIGENCE.PUBLIC; -- Drop the public schema if it exists
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;  -- Schema for holding all agents
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.SERVICES;  -- Schema for holding all cortex services (Analyst, Search, etc.)

-- ####################################################
-- SETUP GRANTS TO SNOWFLAKE INTELLIGENCE
-- ####################################################

USE ROLE SECURITYADMIN;

-- Create Snowflake Intelligence User role
CREATE ROLE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Enables access to Cortex AI functionality
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the Agents schema
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.SERVICES TO ROLE SNOWFLAKE_INTELLIGENCE_USER;  -- Everyone can access the Services schema


-- Create Snowflake Intelligence Admin role
CREATE ROLE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- SI ADMINS can access the SI USER role
GRANT CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;  -- Only SI ADMINS can create agents
GRANT CREATE SEMANTIC VIEW ON SCHEMA SNOWFLAKE_INTELLIGENCE.SERVICES TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- grant create semantic views for cortex analyst to SI ADMINS
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA SNOWFLAKE_INTELLIGENCE.SERVICES TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN; -- grant create cortex search service to SI ADMINS

-- Grant out to the user community
GRANT ROLE SNOWFLAKE_INTELLIGENCE_USER TO ROLE PUBLIC; -- Everyone can use Snowflake Intelligence
CREATE ROLE IF NOT EXISTS AI_SERVICES_DEVELOPER_GROUP ;
GRANT ROLE SNOWFLAKE_INTELLIGENCE_ADMIN TO ROLE AI_SERVICES_DEVELOPER_GROUP; -- AI Engineers can create/monitor AI services
--GRANT ROLE SNOWFLAKE_INTELLIGENCE_ADMIN TO ROLE AI_SERVICES_SECONDARY_GROUP; -- Optional grant to a secondary group


-- ####################################################
-- SETUP GRANTS TO AI SERVICES
-- ####################################################

-- grant usage to PUBLIC services
GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.<PUBLIC_AGENT> TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access the public agent
GRANT USAGE ON CORTEX SEARCH SERVICE SNOWFLAKE_INTELLIGENCE.SERVICES.<PUBLIC_SEARCH_SERVICE> TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access a public search service
GRANT REFERENCES, SELECT ON SEMANTIC VIEW SNOWFLAKE_INTELLIGENCE.SERVICES.<PUBLIC_SEMANTIC_VIEW> TO ROLE SNOWFLAKE_INTELLIGENCE_USER; -- SI USERS can access a public semantic view (cortex analyst)


-- grant limited usage to a custom USE CASE role
CREATE ROLE SNOWFLAKE_INTELLIGENCE_<USE_CASE_ROLE>;  -- EG. SNOWFLAKE_INTELLIGENCE_SALE_INSIGHTS_USER
GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.<USE_CASE_AGENT> TO ROLE CREATE ROLE SNOWFLAKE_INTELLIGENCE_<USE_CASE_ROLE>;  -- CUSTOMER USE CASE role can access a non-public agent
GRANT USAGE ON CORTEX SEARCH SERVICE SNOWFLAKE_INTELLIGENCE.SERVICES.<USE_CASE_SEARCH_SERVICE> TO ROLE SNOWFLAKE_INTELLIGENCE_<USE_CASE_ROLE>; -- CUSTOMER USE CASE role can access a non-public search service
GRANT REFERENCES, SELECT ON SEMANTIC VIEW SNOWFLAKE_INTELLIGENCE.SERVICES.<USE_CASE_VIEW> TO ROLE SNOWFLAKE_INTELLIGENCE_<USE_CASE_ROLE>; -- CUSTOMER USE CASE role can access a non-public semantic view (cortex analyst)


-- SHOW GRANTS TO CORTEX UESR
SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.CORTEX_USER;
SHOW GRANTS OF ROLE SNOWFLAKE_INTELLIGENCE_USER;
SHOW GRANTS OF ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
SHOW GRANTS OF ROLE AI_SERVICES_DEVELOPER_GROUP;
SHOW GRANTS OF ROLE SNOWFLAKE_INTELLIGENCE_<USE_CASE_ROLE>;
